title: AboutAI
description: Anatoly Starostin's blog about AI
author: "Anatoly Starostin"

theme: minima

base_url: /aboutai
repository: anatoli-starostin/aboutai

# Minima social links
github_username: anatoli-starostin
linkedin_username: anatoly-starostin-12109b142

future: true

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages
  - _images

exclude:
  - Gemfile
  - .gitignore
  - README.md
